### ISSUE TITLE
need to check string/not string query handling

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#11]

**Comment by esmyers** [comment]
for the chart queries.

**Comment by esmyers** [comment]
https://github.com/USGS-WiM/sparrow-eastern-us-js/commit/90a92b2a8876d675141366e7f72870e6254e5f22

Eastern U.S. Has the new syntax.  See the commit linked above for the exact code that was replaced.  We need to make sure that line 1234 in Eastern U.S. makes it's way in to the national dissolved solids if it isn't there already.  There are several instances of this sort of check for the where clause throughout the app.  Searching through the code for the function calls will help you locate them.

**Comment by rstevensonUSGS** [comment]
Completed. changes made to NDS per Eriks  comment

**Comment by rstevensonUSGS** [comment]
Complete changes merged to master
