### ISSUE TITLE
check issue of 2 chart bars appearing when there should be 1

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#12]

**Comment by esmyers** [comment]
This is coming from the data.  The queries from the app are doing exactly what they're supposed to.  
![image](https://user-images.githubusercontent.com/2495167/45222746-ef93df80-b27a-11e8-9b18-eee888919409.png)

**Comment by esmyers** [comment]
we should be seeing catchments labeled like this 
![image](https://user-images.githubusercontent.com/2495167/45222873-48fc0e80-b27b-11e8-9f59-37715e326284.png)

**Comment by esmyers** [comment]
email to Jana about fixing data.  Not sure how the data processing works on their end but I suspect that somehow these duplicates may have been created in the process of splitting along state borders.  At any rate, I'm tabling this until her response.

**Comment by HansVraga** [comment]
Jana is updating the data.
