### ISSUE TITLE
Disable auto-shutdown on SparrowTest EC2

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#3]
Ideally I would like to disable the nightly auto shutdown.
Otherwise I would like the instance start very early in the morning so that the cooperators can view the apps.

While we're waiting for our production instance,  I'll continue to use ESRI REST Services on SparrowTest.wim.usgs.gov in the sandbox account.  We'll be ready to move them over to production when we get the production EC2 and approval from cooperators.

**Comment by aaronstephenson** [comment]
Done.
