### ISSUE TITLE
Move Client Version from About title

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-national-dissolved-solids-js#36]
- [x] Park the client version in the "disclaimer" tab, like below:
- [x] Create Issues to do the same for the other Sparrow Interfaces

![image](https://user-images.githubusercontent.com/12058013/46905291-76158f80-cebf-11e8-98ec-6fe03436aedc.png)

**Comment by rstevensonUSGS** [comment]
If it is in the title of the About section ( see image) do we need it also in the disclaimer... or should we remove it from the about header? 

<img width="508" alt="verision" src="https://user-images.githubusercontent.com/22685263/46953173-4f379480-d04a-11e8-944d-0a97ebc9b526.PNG">

**Comment by rstevensonUSGS** [comment]
Complete  for: 
1.) PWS
2.) Eastern US 
3.) NDS 
4.) Midcont

**Comment by rstevensonUSGS** [comment]
I didnt create issues for each of these, but i completed  this task for all the following: 
1.) PNW 
2.) marb
3.) great lakes
4.) Eastern US 
5.) NDS 
6.) Midcont 

Tenn couldn't
<img width="308" alt="issue_36" src="https://user-images.githubusercontent.com/22685263/47090513-4f699880-d1e0-11e8-8a3f-14cb2aeebee5.PNG">
 be done per slack conversation on 10/16/2018
