### ISSUE TITLE
Adjust source colors for surficial lithology and non-US inflow

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-national-dissolved-solids-js#37]
Feedback from cooperator:

2) For charts >   The colors of surficial lithology and non US inflow are too similar, both look like same color of red to me

**Comment by rstevensonUSGS** [comment]
Any suggestion on color choice?

**Comment by esmyers** [comment]
Look at the other interfaces first and see if there are existing colors we're not using for these color bars.  (I think there will be some in the Nitrogen object that we're not using).  Anything that stands out against the currently selected colors will be fine.

**Comment by rstevensonUSGS** [comment]
Green used from Nitrogen color #006800
