### ISSUE TITLE
Adjust color gradient on map for dissolved solids model

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-national-dissolved-solids-js#38]
For consistancy across applications, we should leave the green/brown for phosphorus/nitrogen and pick a new color for dissolved solids (which will be in future sparrow interfaces).

Orange was suggested by cooperator.

**Comment by rstevensonUSGS** [comment]
<img width="889" alt="color_comparision" src="https://user-images.githubusercontent.com/22685263/47297597-b6b58d00-d5d2-11e8-9b06-43d015b73ec4.PNG">

The map on the left hand side, are the color options I thought I'd go with, If those are okay, I will commit and push my changes to master.

**Comment by rstevensonUSGS** [comment]
<img width="730" alt="color_basemap" src="https://user-images.githubusercontent.com/22685263/47307262-defdb580-d5eb-11e8-91b5-5631db899fee.PNG">
 Updated
