### ISSUE TITLE
Change layer name for model results

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-national-dissolved-solids-js#39]
- [x] Change the label "Nutrient model results overlay" to "SPARROW Model Results"

- [ ] Create issues to do this in all other interfaces.

**Comment by rstevensonUSGS** [comment]
The following have been comcpleted: 
1.) PNW
2.) Eastern
3.) Midcont 
4,) great-lakes 
5.) NDS 
6.) MARB
