### ISSUE TITLE
remove radio buttons and test

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#5]

**Comment by rstevensonUSGS** [comment]
for Issue #5 Remove Radio Buttons does that refer to any button that involved Nitrogen, cause we dont have the data correct? or is that not right?

**Comment by esmyers** [comment]
Correct. We'll treat everything in this model as if it is Phosphorus.  So Nitrogen references can be removed.  I think you'll want to start by just removing the radio button from the HTML.  Some of the JS logic relies on testing which radio button is checked.  So you may have to look for references to the radio1 button id throughout the code.

**Comment by rstevensonUSGS** [comment]
Okay, so far I have removed the buttons from the data download that includes Nitrogen for shape files and calibration sites. and under Data filter Total Nitrogen. I am going to see if I can remove any reference to Nitrogen from the Map Layers section.

**Comment by rstevensonUSGS** [comment]
Yeah, That Makes sense. hahah
