### ISSUE TITLE
update about window with Jana's Changes

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#58]
See Jana's email attachment for the changes laid out in red.

**Comment by rstevensonUSGS** [comment]
This was doine but there is a discrepency between her changes and what the actual HUCs are for the application. See Images 

Image 1: Janas Changes in the About Document 
<img width="428" alt="sparrow_nds_about" src="https://user-images.githubusercontent.com/22685263/48168930-8ba78a80-e2ae-11e8-97fd-367a2d96159e.PNG">

Image 2: The Spreadsheet That came with the shapefile
<img width="601" alt="sparrow_nds_ss" src="https://user-images.githubusercontent.com/22685263/48168950-9a8e3d00-e2ae-11e8-8b17-949a1483b61e.PNG">
