### ISSUE TITLE
clicking 'always on' checkbox still turns data on/off

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#63]
![image](https://user-images.githubusercontent.com/2495167/48209335-7b3cf180-e33a-11e8-8076-ef36f6682d2d.png)
the checkbox is always on, but clicking it turns the layer on and off.

**Comment by rstevensonUSGS** [comment]
I am confused, I just tired it in test and in production  and i can't click on the sparrow model results at all,  a No  symbol shows up over that area so you can't click it. What am I missing?

**Comment by esmyers** [comment]
@rstevensonUSGS The issue seems to be that we disabled clicking on the larger label button area that includes the checkbox and label.  But the checkbox itself will still toggle the layer on and off.  It seems that the checkbox has a different event structure and it doesn't have an e.currentTarget.id.  (even though that works for the label area).

**Comment by esmyers** [comment]
What we need to do is dig a little deeper into the event.  I changed the check to:  `e.currentTarget.firstElementChild.id != "SparrowRanking"` and it worked as expected.

**Comment by esmyers** [comment]
@rstevensonUSGS I have this fixed in NDS and will update it next time I push, but you can add it to a different app and update.  Let's test this one carefully before we do all the other apps.

**Comment by esmyers** [comment]
> I am confused, I just tired it in test and i can't click on the sparrow model results at all, a No symbol shows up over that area so you can't click it. What am I missing?
