### ISSUE TITLE
check FLUXMASTER in calibration site popup

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#72]
I'm not seeing a value in the popup.   Maybe there is no fluxmaster? We should verify this and remove it from the infoWindow Template in the code.

FIELDS IN NDS CALIBRATION SITES
OBJECTID ( type: esriFieldTypeOID , alias: OBJECTID )
Shape ( type: esriFieldTypeGeometry , alias: Shape )
STAID ( type: esriFieldTypeString , alias: STAID , length: 254 )
SNAME ( type: esriFieldTypeString , alias: SNAME , length: 254 )
Latitude ( type: esriFieldTypeDouble , alias: Latitude )
Longitude ( type: esriFieldTypeDouble , alias: Longitude )
SPAR_NUM ( type: esriFieldTypeDouble , alias: SPAR_NUM )
REACH_NUM ( type: esriFieldTypeDouble , alias: REACH_NUM )

**Comment by rstevensonUSGS** [comment]
Removed  from info window section of code.
