### ISSUE TITLE
Content updates for go-live

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-national-dissolved-solids-js#75]
- [x]  Title:  Drop the word "concentrations" from title since we are not actually mapping concentrations, so new title would be:

>Dissolved Solids Sources, Loads, and Yields For the Conterminous U.S.  

- [x] Make the same change for the title  on the ABOUT tab title

- [x] Since Steve Preston is retiring at the end of January and Dave Saad taking over, please change the contact information to be David Saad

(About TAB  - contact information)

> 
> David Saad
> Hydrologist 
> 608-821-3865
> dasaad@usgs.gov 
> https://www.usgs.gov/staff-profiles/david-a-saad
> 
> USGS Upper Midwest Water Science Center
> 8505 Research Way
> Middleton, WI 53562
> https://www.usgs.gov/centers/wisconsin-water-science-center

- [ ] ABOUT TAB > Definitions
 Add a short sentence _as shown in italics_ to the following paragraph.   

> Incremental Load 
> The predicted mean annual load of the constituent (kilograms per year) leaving a stream reach that reflects only those sources contributed from within the incremental drainage area of that reach. The incremental load value includes the effects of in-stream attenuation processes associated with one half of the incremental reach length. Incremental drainage areas are represented here as “catchments”.  _For the purposes of mapping, all lithology source variables were aggregated into a single source variable, called lithology,with the exception of water (submerged lithologies)._
>

**Comment by rstevensonUSGS** [comment]
Completed
